name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Rename File
        run: mv resume.pdf jeanney-anthony-cv.pdf
      - name: Create PDF Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: jeanney-anthony-cv.pdf
          tag: latest
          overwrite: true
      # - name: SCP Copy
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     overwrite: true
      #     source: "jeanney-anthony-cv.pdf"
      #     target: "~/personnal-web-page/public"
